import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import useBearStore from '@/store'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter'
})

export default function Home() {
  function BearCounter() {
    const bears = useBearStore((state) => state.bears)
    return <h1>{bears} around here ...</h1>
  }

  function Controls() {
    const increasePopulation = useBearStore((state) => state.increase)
    return <button onClick={() => increasePopulation(1)}>one up</button>
  }

  return (
    <>
      <Head>
        <title>Initiate Agency Blog Starter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.variable} font-sans`}>
        <div className="p-28">
          <h1 className="text-9xl font-bold text-green-600 underline">Hello world!</h1>
          <BearCounter />
          <Controls />
        </div>
      </main>
    </>
  )
}
